pipeline {
    agent any

    environment {
        EC2_HOST = '44.221.77.210'
        SSH_CREDENTIALS_ID = 'EC2_PEM_KEY'
        REPO_URL = 'https://github.com/Akashsingh86500/JOVAC-CICD-pipeline-jenkins.git'
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Deploy service-a') {
            steps {
                sshagent(credentials: [env.SSH_CREDENTIALS_ID]) {
                    // Reads the script from the root 'scripts' folder and executes it on EC2
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@${EC2_HOST} \
                        "REPO_URL=${REPO_URL} bash -s service-a" < scripts/deploy_app.sh
                    """
                }
            }
        }
    }
}