pipeline {
  agent any

  environment {
    EC2_HOST = '3.27.239.46'
    SSH_CREDENTIALS_ID = 'EC2_PEM_KEY'
    REPO_URL = 'https://github.com/Akashsingh86500/JOVAC-CICD-pipeline-jenkins.git'
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Create Python venv & Install Requirements') {
      steps {
        sh '''
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
        '''
      }
    }

    stage('Deploy service-b') {
      steps {
        sshagent(credentials: [env.SSH_CREDENTIALS_ID]) {
          sh """
            ssh -o StrictHostKeyChecking=no ubuntu@${EC2_HOST} \
            \\"REPO_URL=${REPO_URL} bash -s service-b\\" < scripts/deploy_app.sh
          """
        }
      }
    }
  }
}
